server:
  port: 8888

spring:
  application:
    name: chun-ai
  ai:
    dashscope:
      api-key: ${SPRING_AI_DASHSCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v4
      chat:
        options:
          model: qwen3-max
    vectorstore:
      qdrant:
        host: ${SPRING_AI_VECTORSTORE_QDRANT_HOST:localhost}
        port: ${SPRING_AI_VECTORSTORE_QDRANT_PORT:6334}
        use-tls: false
        # api-key: ${SPRING_AI_VECTORSTORE_QDRANT_API_KEY:}
        collection-name: chun_ai
        initialize-schema: true

search-api:
  api-key: ${SEARCH_API_API_KEY}
